server:
  port: 8080
spring:
    datasource:
      druid:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mysql_travel?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
#
#logging:
#  level:
#    com.navigation: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
#logging:
#  level:
#    root: DEBUG




mybatis:
  #mapper配置文
  mapper-locations: classpath:/*.xml
  type-aliases-package: com.navigation.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

knife4j:
  enable: true
  openapi:
    title: 唐十八陵导览系统接口文档
    description: " 唐十八陵导览系统接口文档"
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          com.navigation.controller

