server:
  port: 8080
spring:

    datasource:
      druid:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/navigation_system?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456

    redis:
      host: 47.96.179.70 # 更换成自己的地址
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms

    mail:
      protocol: smtp # 邮件协议
      host: smtp.163.com #网易邮箱 smtp 服务器地址
      port: 25
      username: 18794295151@163.com  #发件人邮箱地址
      password: YJaPC9HSPpNh3mVF #授权码
      default-encoding: UTF-8 #编码字符集
      properties:
        mail:
          debug:true #开启debug后，会完整打印邮件发送过程的日志


    thymeleaf:
      prefix: classpath:/templates/  # 模板文件存放的路径
      suffix: .html  # 模板文件的扩展名
      mode: HTML  # 模板的模式，通常是 HTML
      encoding: UTF-8  # 模板文件的编码
      cache: false  # 在开发时禁用缓存


    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
logging:
  level:
    com.navigation: debug
  pattern:
    dateformat: HH:mm:ss:SSS



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 确保驼峰命名开启

knife4j:
  enable: true
  openapi:
    title: 唐十八陵导览系统接口文档
    description: " 唐十八陵导览系统接口文档"
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          com.navigation.controller

