server:
  port: 8080
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mysql_travel?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  mail:
    protocol: smtp # 邮件协议
    host: smtp.163.com #网易邮箱 smtp 服务器地址
    port: 25
    username: 18794295151@163.com  #发件人邮箱地址
    password: YJaPC9HSPpNh3mVF #授权码
    default-encoding: UTF-8 #编码字符集
    properties:
      mail:
        debug:true #开启debug后，会完整打印邮件发送过程的日志


    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
      encoding: UTF-8
      cache: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: 127.20.10.8
    port: 6379
    password: 123456
    database: 0
    timeout: 2000
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 2
        max-wait: 10000
baidu:
  yingyan:
    ak: "aaM0EeonjbNkG4x5dfAlEdlIz04Jso5z"
    service-id: "241558"
    base-url: "http://yingyan.baidu.com/api/v3"

http:
  maxTotal: 300
  defaultMaxPerRoute: 50
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 5000
  staleConnectionCheckEnabled: true
#logging:
#  level:
#    com.navigation: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
logging:
  level:
    root: DEBUG




mybatis:
  #mapper配置文
  mapper-locations: classpath:/*.xml
  type-aliases-package: com.navigation.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

knife4j:
  enable: true
  openapi:
    title: 唐十八陵导览系统接口文档
    description: " 唐十八陵导览系统接口文档"
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          com.navigation.controller

