server:
  port: 8080
spring:
    datasource:
      druid:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/navigation_system?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456

    mail:
      protocol: smtp # 邮件协议
      host: smtp.163.com #网易邮箱 smtp 服务器地址
      port: 25
      username: 18794295151@163.com  #发件人邮箱地址
      password: YJaPC9HSPpNh3mVF #授权码
      default-encoding: UTF-8 #编码字符集
      properties:
        mail:
          debug:true #开启debug后，会完整打印邮件发送过程的日志

    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
logging:
  level:
    com.navigation: debug
  pattern:
    dateformat: HH:mm:ss:SSS



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 确保驼峰命名开启

knife4j:
  enable: true
  openapi:
    title: 唐十八陵导览系统接口文档
    description: " 唐十八陵导览系统接口文档"
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          com.navigation.controller

